version: "3.7"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker/volumes/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
